# Generated by Django 5.2 on 2025-04-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.IntegerField()),
                ('j', models.IntegerField()),
                ('p', models.IntegerField()),
                ('e', models.IntegerField()),
                ('mp', models.IntegerField(null=True)),
                ('me', models.IntegerField(null=True)),
                ('boat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boats.boat')),
            ],
        ),
    ]
