# Generated by Django 5.2 on 2025-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saildata',
            name='imperial_or_metric',
            field=models.CharField(choices=[('imperial', 'Imperial'), ('metric', 'Metric')], default='metric', max_length=10),
        ),
    ]
