# Generated by Django 5.2 on 2025-04-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_saildata_imperial_or_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='variant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
