# Generated by Django 5.2 on 2025-04-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0003_alter_boat_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='me',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='mp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
