# Generated by Django 5.2 on 2025-04-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_alter_boat_variant_alter_saildata_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saildata',
            name='e',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='i',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='j',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='me',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='mp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='p',
            field=models.FloatField(),
        ),
    ]
