# Generated by Django 5.2 on 2025-04-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_alter_saildata_e_alter_saildata_i_alter_saildata_j_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
