# Generated by Django 5.2 on 2025-04-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_alter_boat_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='saildata',
            name='mizzen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boat',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='i',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='j',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saildata',
            name='p',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
