# Generated by Django 5.2 on 2025-04-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0007_saildata_mizzen_alter_boat_make_alter_boat_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saildata',
            name='imperial_or_metric',
            field=models.CharField(choices=[('imperial', 'Imperial'), ('metric', 'Metric')], default='imperial', max_length=10),
        ),
    ]
